@startuml

class UserEntity {
    +Long id
    +int version
    +Instant created
    +Instant lastUpdated
    +String email
    +String passwordHash
    +String firstName
    +String lastName
}

class ClientEntity {
    +Long id
    +int version
    +Instant created
    +Instant lastUpdated
    +UserEntity user
    +List<AppointmentEntity> appointments
}

class SpecialistEntity {
    +Long id
    +int version
    +Instant created
    +Instant lastUpdated
    +UserEntity user
    +Specialization specialization
    +List<TreatmentEntity> treatments
}

class TreatmentEntity {
    +Long id
    +int version
    +Instant created
    +Instant lastUpdated
    +String name
    +String description
    +int durationMinutes
    +SpecialistEntity specialist
}

class AppointmentEntity {
    +Long id
    +int version
    +Instant created
    +Instant lastUpdated
    +ClientEntity client
    +TreatmentEntity treatment
    +Instant dateTime
    +Instant endsAt
    +AppointmentStatus status
}

enum AppointmentStatus {
    SCHEDULED
    CANCELLED
    COMPLETED
}

enum Specialization {
    DENTIST("Dentist") 
	CARDIOLOGIST("Cardiologist") 
	PEDIATRICIAN("Pediatrician") 
	UROLOGIST("Urologist")
	NEUROLOGIST("Neurologist") 
	ORTHOPAEDIST("Orthopaedist")
}

Client "1" -- "1" User 
Client "1" -- "n" Appointment 
Specialist "1" -- "1" User
Specialist "1" -- "n" Treatment 
Treatment "1" -- "n" Appointment 

@enduml